name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
    
env:
  DOCKER_IMG_NAME: ${GITHUB_SHA::7}
  
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
    
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: make application-aws.properties      # 프로퍼티 작성
      run: |
        cd ./src/main/resources             
        echo "${{ secrets.PROPERTIES }}" > ./application.properties
      shell: bash
      
    - name: Grant execute permission for gradlew    # 실행권한 부여
      run: chmod +x ./gradlew
      shell: bash
    
    - name: Build with Gradle               # gradle 프로젝트 빌드
      run: ./gradlew clean build
      shell: bash 

    - name: Docker Hub 로그인
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - uses: actions/checkout@v3           
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_IMG_NAME .
#       docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Docker Hub 이미지 push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_IMG_NAME
    
    
    - name: Configure AWS credentials                  # aws 인증
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}                  # github-settings-secrets-actions-Repository secrets에 등록
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        script: |
            docker stop $(docker ps -a -q) 
            docker rm $(docker ps -a -q) 
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_IMG_NAME
            docker run -d -p 8080:8080 --name ${{ secrets.DOCKER_CONTAINER_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_IMG_NAME
        
